project_id = "dvmftknddmssmpyhnjob"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.payfast-notify]
verify_jwt = false

[functions.payfast-create]
verify_jwt = false

[functions.payment-status]
verify_jwt = false

[functions.download-track]
verify_jwt = false
