project_id = "dvmftknddmssmpyhnjob"

[functions.preview-transactional-email]
verify_jwt = false

[functions.payfast-notify]
verify_jwt = false

[functions.payfast-create]
verify_jwt = false

[functions.payment-status]
verify_jwt = false

[functions.download-track]
verify_jwt = false

[functions.palesa-front-desk]
verify_jwt = false

[functions.content-api]
verify_jwt = false

[functions.send-outbox-email]
verify_jwt = true
