import * as React from 'npm:react@18.3.1'
import {
  Body, Container, Head, Heading, Html, Preview, Section, Text,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

const SITE_NAME = 's2kDOTza Entertainment'

interface MetaRuleRow {
  rule_name: string
  attempts: number
  retries: number
  retry_rate_pct: number
  dlq_count: number
  dlq_rate_pct: number
  retry_rate_delta_pct: number
  dlq_rate_delta_pct: number
}

interface Props {
  date?: string
  windowHours?: number
  topByAttempts?: MetaRuleRow[]
  topByRetrySpike?: MetaRuleRow[]
  topByDlqChange?: MetaRuleRow[]
  totals?: {
    total_attempts: number
    total_retries: number
    total_dlq: number
  }
}

const fmt = (n: number) => Math.round(n * 100) / 100

const Row = ({ r }: { r: MetaRuleRow }) => (
  <Text style={text}>
    <strong>{r.rule_name}</strong> — attempts: {r.attempts} · retry%: {fmt(r.retry_rate_pct)}
    {' '}(Δ {fmt(r.retry_rate_delta_pct)}) · DLQ%: {fmt(r.dlq_rate_pct)} (Δ {fmt(r.dlq_rate_delta_pct)})
  </Text>
)

const SecurityDailyReportEmail = ({
  date, windowHours, topByAttempts, topByRetrySpike, topByDlqChange, totals,
}: Props) => {
  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>Security alert delivery digest — {date}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>Security alert delivery digest</Heading>
          <Text style={muted}>
            {date} · last {windowHours ?? 24}h · compared to prior {windowHours ?? 24}h window
          </Text>

          <Section style={panel}>
            <Text style={text}>
              <strong>Totals (last {windowHours ?? 24}h):</strong> {totals?.total_attempts ?? 0} attempts ·
              {' '}{totals?.total_retries ?? 0} retries · {totals?.total_dlq ?? 0} DLQ
            </Text>
          </Section>

          <Heading style={h2}>Top meta-rules by attempt volume</Heading>
          {(topByAttempts ?? []).length === 0
            ? <Text style={muted}>No attempts recorded.</Text>
            : (topByAttempts ?? []).map((r, i) => <Row key={i} r={r} />)}

          <Heading style={h2}>Retry spikes</Heading>
          {(topByRetrySpike ?? []).length === 0
            ? <Text style={muted}>No retry spikes detected.</Text>
            : (topByRetrySpike ?? []).map((r, i) => <Row key={i} r={r} />)}

          <Heading style={h2}>DLQ rate changes</Heading>
          {(topByDlqChange ?? []).length === 0
            ? <Text style={muted}>No DLQ rate changes detected.</Text>
            : (topByDlqChange ?? []).map((r, i) => <Row key={i} r={r} />)}

          <Text style={footer}>
            Source: security_alert_dispatch_log + security_alert_dlq (auto-generated by
            security-daily-report). Tune cooldowns and destinations in the Security tab to address spikes.
          </Text>
          <Text style={signature}>— {SITE_NAME}</Text>
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: SecurityDailyReportEmail,
  subject: (data: Record<string, any>) =>
    `Security alert digest — ${(data?.date as string) || 'today'}`,
  displayName: 'Security daily report (auto)',
  previewData: {
    date: '2026-06-01',
    windowHours: 24,
    totals: { total_attempts: 142, total_retries: 18, total_dlq: 3 },
    topByAttempts: [
      { rule_name: 'retry-rate watcher', attempts: 96, retries: 12, retry_rate_pct: 12.5, dlq_count: 2, dlq_rate_pct: 2.1, retry_rate_delta_pct: 4.2, dlq_rate_delta_pct: 1.1 },
    ],
    topByRetrySpike: [
      { rule_name: 'retry-rate watcher', attempts: 96, retries: 12, retry_rate_pct: 12.5, dlq_count: 2, dlq_rate_pct: 2.1, retry_rate_delta_pct: 8.0, dlq_rate_delta_pct: 0 },
    ],
    topByDlqChange: [
      { rule_name: 'dlq watcher', attempts: 46, retries: 6, retry_rate_pct: 13.0, dlq_count: 1, dlq_rate_pct: 2.2, retry_rate_delta_pct: 0, dlq_rate_delta_pct: 1.8 },
    ],
  },
} satisfies TemplateEntry

const main = { backgroundColor: '#ffffff', fontFamily: '"DM Sans", Arial, sans-serif', margin: 0, padding: 0 }
const container = { maxWidth: '640px', margin: '0 auto', padding: '32px 24px' }
const h1 = { fontFamily: '"Playfair Display", Georgia, serif', fontSize: '24px', fontWeight: 700, color: '#0a0a0a', margin: '0 0 8px', lineHeight: 1.3 }
const h2 = { fontFamily: '"Playfair Display", Georgia, serif', fontSize: '16px', fontWeight: 700, color: '#0a0a0a', margin: '24px 0 8px' }
const text = { fontSize: '14px', color: '#2a2a2a', lineHeight: 1.6, margin: '0 0 8px' }
const muted = { fontSize: '13px', color: '#6a6a6a', lineHeight: 1.5, margin: '0 0 12px' }
const panel = { backgroundColor: '#f7f7f7', padding: '12px 16px', borderRadius: '6px', margin: '12px 0 4px' }
const footer = { fontSize: '12px', color: '#6a6a6a', lineHeight: 1.5, margin: '24px 0 8px' }
const signature = { fontSize: '14px', color: '#0a0a0a', fontWeight: 600, margin: 0 }
